### ISSUE TITLE
IndexConnection should allow for more configuration of the gRPC client

### ISSUE THREAD

**Issue by haruska** [pinecone-io/go-pinecone#13]
Probably we will need to configure some additional configs here for stuff like timeouts, custom certs, etc. They are poorly tested / documented because they predate me, but the python client has a [number of different things](https://github.com/pinecone-io/pinecone-python-client/blob/main/pinecone/grpc/config.py) that can be configured for grpc.

_Originally posted by @jhamon in https://github.com/pinecone-io/go-pinecone/pull/11#discussion_r1511610741_

**Comment by anawishnoff** [comment]
This is available in the latest release, closing now.
