### ISSUE TITLE
[Bug] Unusual use of *context.Context

### ISSUE THREAD

**Issue by robfig** [pinecone-io/go-pinecone#19]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Updating from v0.3 to v0.4, I like the new API, much easier to use. Nice work!

However, I did notice that the API methods all accept a `*context.Context` instead of a `context.Context`. That is highly unusual. Every other usage of context.Context inside the stdlib and other API clients is `context.Context`, which makes me think it was unintentional. Taking address-of to satisfy the interface is no big deal, but it does seem like an API design error. 

### Expected Behavior

Use context.Context, instead of a pointer to that interface.

### Steps To Reproduce

N/A

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by austin-denoble** [comment]
Thanks for the callout, @robfig. I think you're right, I've got a PR up to tweak the API: https://github.com/pinecone-io/go-pinecone/pull/20

Props to @haruska for getting the improved v0.4 client released!

**Comment by austin-denoble** [comment]
`v0.5.0` has been released which should address this. Thanks again! https://github.com/pinecone-io/go-pinecone/releases/tag/v0.5.0
